IF OBJECT_ID ('TEMPDB..##PREPAYS')
IS NOT NULL
	DROP TABLE ##PREPAYS;
SELECT 
AIL.INVOICE_ID, 
AI.INVOICE_NUM,
AIL.LINE_NUMBER INVOICE_LINE_NUMBER,
--AIL.ORG_ID,
AIL.PREPAY_INVOICE_ID,
AIL.ACCOUNTING_DATE, 
AIL.PERIOD_NAME,
(-1)*(AIL.AMOUNT - ISNULL(AIL.INCLUDED_TAX_AMOUNT,0))PREPAY_AMOUNT_APPLIED,
NULLIF((-1)*(ISNULL(AIL.TOTAL_REC_TAX_AMOUNT, 0) + ISNULL(AIL.TOTAL_NREC_TAX_AMOUNT, 0)), 0)TAX_AMOUNT_APPLIED,
AIL.SET_OF_BOOKS_ID,
AIL.DESCRIPTION ,
AIL.LINE_TYPE_LOOKUP_CODE,
AI.VENDOR_ID,
AI.VENDOR_SITE_ID,
AI.INVOICE_CURRENCY_CODE

INTO ##PREPAYS
FROM
STAGING..EBS_AP_INVOICE_LINES_ALL AIL JOIN STAGING..EBS_AP_INVOICES_ALL AI
ON (AIL.INVOICE_ID = AI.INVOICE_ID)
WHERE AIL.AMOUNT  < 0
AND ISNULL(AIL.DISCARDED_FLAG,'N') <> 'Y'
AND AIL.LINE_TYPE_LOOKUP_CODE  = 'PREPAY'
AND AI.INVOICE_TYPE_LOOKUP_CODE NOT IN ('PREPAYMENT', 'CREDIT','DEBIT')

UNION


	SELECT
	AILA.INVOICE_ID,
	AI.INVOICE_NUM,
	APD.INVOICE_LINE_NUMBER, --agregarla a la otra
	APD.INVOICE_ID    PREPAY_INVOICE_ID,
	AILA.ACCOUNTING_DATE,
	AILA.PERIOD_NAME,
	PAP.PREPAY_AMOUNT_APPLIED,
	TXA.TAX_AMOUNT_APPLIED,
	AILA.SET_OF_BOOKS_ID,
	AILA.DESCRIPTION ,
	aila.LINE_TYPE_LOOKUP_CODE			as aila_line,
	--APD.LINE_TYPE_LOOKUP_CODE    as apd_line,
	AI.VENDOR_ID,
	AI.VENDOR_SITE_ID,
	AI.INVOICE_CURRENCY_CODE

FROM
STAGING..EBS_AP_INVOICE_LINES_ALL AILA 
JOIN STAGING..EBS_AP_INVOICES_ALL AI 					ON (AILA.INVOICE_ID = AI.INVOICE_ID)
JOIN STAGING..EBS_AP_INVOICE_DISTRIBUTIONS_all APD  	ON( AILA.INVOICE_ID = APD.INVOICE_ID)
AND 
APD.INVOICE_LINE_NUMBER = AILA.LINE_NUMBER --es numeric 22,0 / iln tiene 22,2
join ##TAX_AMOUNT_APP TXA on (TXA.INVOICE_ID = APD.INVOICE_ID)
join ##PREPAY_AMOUNT_APP PAP ON (PAP.INVOICE_ID = APD.INVOICE_ID)
WHERE 
AILA.LINE_TYPE_LOOKUP_CODE = 'ITEM' --HASTA ACA fUNCA
AND APD.LINE_TYPE_LOOKUP_CODE = 'PREPAY'
AND ISNULL(AILA.DISCARDED_FLAG, 'N') <> 'Y'
AND AI.INVOICE_TYPE_LOOKUP_CODE NOT IN  ('PREPAYMENT', 'CREDIT', 'DEBIT')



;